### ISSUE TITLE
Redis doesn't work respectively blocks

### ISSUE THREAD

**Issue by Sascha89** [eventerza/eventerza#1]
Predis package is missing in composer.json:

"require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.2.*",
    "eventerza/user-management": "dev-feature/basic-setup",
    "predis/predis": "~1.0"
},

https://laravel.com/docs/5.2/redis#introduction

and ports are not well configured:
php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://redis:6379]

'redis' => [

    'cluster' => false,

    'default' => [
        'host' => env('REDIS_HOST', 'localhost'),
        'password' => env('REDIS_PASSWORD', null),
        'port' => env('REDIS_PORT', 6379),
        'database' => 0,
    ],

],

**Comment by mc388** [comment]
It's not a bug, you have to run you application with the given docker setup
